### ISSUE TITLE
the code mean I don't konw

### ISSUE THREAD

**Issue by lgl1227** [GorgeousYUROU/DCGAN-inpainting#1]
def convert_to_lower_resolution():
    images=glob(os.path.join('cars_train\cars_train/','*.jpg'))
    i=0
    size=108,108
    for image in images:

        im=Image.open(image)
        im_resized=im.resize(size,Image.ANTIALIAS)
        im_resized.save("cars_train/"+str(i)+'.jpg')

cars_train\cars_train/ ??
what is the directory tree ?

**Comment by lgl1227** [comment]
Sorry,I know.
It's cool code.

**Comment by matyle** [comment]
what do you mean cool code
